version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: "django_container"
    container_name: "python_django_container"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db_container
    tty: true

  db_container:
    image: postgis/postgis
    volumes:
      - ./data:/data
    container_name: "db_container"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***********
    ports:
      - 5666:5432

volumes:
  postgres_data:
