# Generated by Django 5.0.6 on 2024-05-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_zasadzki_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zasadzki',
            name='ids',
        ),
    ]
