# Generated by Django 5.0.6 on 2024-06-01 00:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_zasadzki_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'zasadzki',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='zasadzki',
            options={'managed': False},
        ),
    ]
