# Generated by Django 5.0.6 on 2024-06-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_alter_zasadzki_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zasadzki',
            table='zasadzki',
        ),
    ]
